<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WordFrequencyApp.Application\WordFrequencyApp.Application.csproj" />
    <ProjectReference Include="..\WordFrequencyApp.Domain\WordFrequencyApp.Domain.csproj" />
    <ProjectReference Include="..\WordFrequencyApp.Infrastructure\WordFrequencyApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
